// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/wadoh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse_Status int32

const (
	StatusResponse_STATUS_UNKNOWN      StatusResponse_Status = 0
	StatusResponse_STATUS_ACTIVE       StatusResponse_Status = 1
	StatusResponse_STATUS_DISCONNECTED StatusResponse_Status = 2
	StatusResponse_STATUS_NOT_FOUND    StatusResponse_Status = 3
)

// Enum value maps for StatusResponse_Status.
var (
	StatusResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACTIVE",
		2: "STATUS_DISCONNECTED",
		3: "STATUS_NOT_FOUND",
	}
	StatusResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":      0,
		"STATUS_ACTIVE":       1,
		"STATUS_DISCONNECTED": 2,
		"STATUS_NOT_FOUND":    3,
	}
)

func (x StatusResponse_Status) Enum() *StatusResponse_Status {
	p := new(StatusResponse_Status)
	*p = x
	return p
}

func (x StatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wadoh_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_wadoh_proto_enumTypes[0]
}

func (x StatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_Status.Descriptor instead.
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{2, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_wadoh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=StatusResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_wadoh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetStatus() StatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return StatusResponse_STATUS_UNKNOWN
}

type RegisterDeviceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PushNotification bool                   `protobuf:"varint,2,opt,name=push_notification,json=pushNotification,proto3" json:"push_notification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeviceRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPushNotification() bool {
	if x != nil {
		return x.PushNotification
	}
	return false
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qr            *string                `protobuf:"bytes,1,opt,name=qr,proto3,oneof" json:"qr,omitempty"`
	PairCode      *string                `protobuf:"bytes,2,opt,name=pair_code,json=pairCode,proto3,oneof" json:"pair_code,omitempty"`
	LoggedIn      *bool                  `protobuf:"varint,3,opt,name=loggedIn,proto3,oneof" json:"loggedIn,omitempty"`
	Jid           *string                `protobuf:"bytes,4,opt,name=jid,proto3,oneof" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_proto_wadoh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterDeviceResponse) GetQr() string {
	if x != nil && x.Qr != nil {
		return *x.Qr
	}
	return ""
}

func (x *RegisterDeviceResponse) GetPairCode() string {
	if x != nil && x.PairCode != nil {
		return *x.PairCode
	}
	return ""
}

func (x *RegisterDeviceResponse) GetLoggedIn() bool {
	if x != nil && x.LoggedIn != nil {
		return *x.LoggedIn
	}
	return false
}

func (x *RegisterDeviceResponse) GetJid() string {
	if x != nil && x.Jid != nil {
		return *x.Jid
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *SendMessageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendImageMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImageMessageRequest) Reset() {
	*x = SendImageMessageRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImageMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImageMessageRequest) ProtoMessage() {}

func (x *SendImageMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImageMessageRequest.ProtoReflect.Descriptor instead.
func (*SendImageMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{6}
}

func (x *SendImageMessageRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *SendImageMessageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendImageMessageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SendImageMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type SendImageMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImageMessageResponse) Reset() {
	*x = SendImageMessageResponse{}
	mi := &file_proto_wadoh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImageMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImageMessageResponse) ProtoMessage() {}

func (x *SendImageMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImageMessageResponse.ProtoReflect.Descriptor instead.
func (*SendImageMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{7}
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_proto_wadoh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{8}
}

func (x *EventMessage) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *EventMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EventMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{9}
}

func (x *GetWebhookRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

type GetWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookResponse) Reset() {
	*x = GetWebhookResponse{}
	mi := &file_proto_wadoh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookResponse) ProtoMessage() {}

func (x *GetWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{10}
}

func (x *GetWebhookResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetWebhookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveWebhookRequest) Reset() {
	*x = SaveWebhookRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWebhookRequest) ProtoMessage() {}

func (x *SaveWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWebhookRequest.ProtoReflect.Descriptor instead.
func (*SaveWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{11}
}

func (x *SaveWebhookRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *SaveWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_proto_wadoh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wadoh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_wadoh_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteWebhookRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

var File_proto_wadoh_proto protoreflect.FileDescriptor

const file_proto_wadoh_proto_rawDesc = "" +
	"\n" +
	"\x11proto/wadoh.proto\"\a\n" +
	"\x05Empty\"!\n" +
	"\rStatusRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"\xa0\x01\n" +
	"\x0eStatusResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.StatusResponse.StatusR\x06status\"^\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13STATUS_DISCONNECTED\x10\x02\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x03\"Z\n" +
	"\x15RegisterDeviceRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12+\n" +
	"\x11push_notification\x18\x02 \x01(\bR\x10pushNotification\"\xb1\x01\n" +
	"\x16RegisterDeviceResponse\x12\x13\n" +
	"\x02qr\x18\x01 \x01(\tH\x00R\x02qr\x88\x01\x01\x12 \n" +
	"\tpair_code\x18\x02 \x01(\tH\x01R\bpairCode\x88\x01\x01\x12\x1f\n" +
	"\bloggedIn\x18\x03 \x01(\bH\x02R\bloggedIn\x88\x01\x01\x12\x15\n" +
	"\x03jid\x18\x04 \x01(\tH\x03R\x03jid\x88\x01\x01B\x05\n" +
	"\x03_qrB\f\n" +
	"\n" +
	"_pair_codeB\v\n" +
	"\t_loggedInB\x06\n" +
	"\x04_jid\"P\n" +
	"\x12SendMessageRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"q\n" +
	"\x17SendImageMessageRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\"\x1a\n" +
	"\x18SendImageMessageResponse\"N\n" +
	"\fEventMessage\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"%\n" +
	"\x11GetWebhookRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"D\n" +
	"\x12GetWebhookResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"8\n" +
	"\x12SaveWebhookRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"(\n" +
	"\x14DeleteWebhookRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid2\xb6\x03\n" +
	"\x11ControllerService\x12)\n" +
	"\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12C\n" +
	"\x0eRegisterDevice\x12\x16.RegisterDeviceRequest\x1a\x17.RegisterDeviceResponse0\x01\x12*\n" +
	"\vSendMessage\x12\x13.SendMessageRequest\x1a\x06.Empty\x12G\n" +
	"\x10SendImageMessage\x12\x18.SendImageMessageRequest\x1a\x19.SendImageMessageResponse\x12)\n" +
	"\x0eReceiveMessage\x12\x06.Empty\x1a\r.EventMessage0\x01\x125\n" +
	"\n" +
	"GetWebhook\x12\x12.GetWebhookRequest\x1a\x13.GetWebhookResponse\x12*\n" +
	"\vSaveWebhook\x12\x13.SaveWebhookRequest\x1a\x06.Empty\x12.\n" +
	"\rDeleteWebhook\x12\x15.DeleteWebhookRequest\x1a\x06.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_wadoh_proto_rawDescOnce sync.Once
	file_proto_wadoh_proto_rawDescData []byte
)

func file_proto_wadoh_proto_rawDescGZIP() []byte {
	file_proto_wadoh_proto_rawDescOnce.Do(func() {
		file_proto_wadoh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wadoh_proto_rawDesc), len(file_proto_wadoh_proto_rawDesc)))
	})
	return file_proto_wadoh_proto_rawDescData
}

var file_proto_wadoh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wadoh_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_wadoh_proto_goTypes = []any{
	(StatusResponse_Status)(0),       // 0: StatusResponse.Status
	(*Empty)(nil),                    // 1: Empty
	(*StatusRequest)(nil),            // 2: StatusRequest
	(*StatusResponse)(nil),           // 3: StatusResponse
	(*RegisterDeviceRequest)(nil),    // 4: RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),   // 5: RegisterDeviceResponse
	(*SendMessageRequest)(nil),       // 6: SendMessageRequest
	(*SendImageMessageRequest)(nil),  // 7: SendImageMessageRequest
	(*SendImageMessageResponse)(nil), // 8: SendImageMessageResponse
	(*EventMessage)(nil),             // 9: EventMessage
	(*GetWebhookRequest)(nil),        // 10: GetWebhookRequest
	(*GetWebhookResponse)(nil),       // 11: GetWebhookResponse
	(*SaveWebhookRequest)(nil),       // 12: SaveWebhookRequest
	(*DeleteWebhookRequest)(nil),     // 13: DeleteWebhookRequest
}
var file_proto_wadoh_proto_depIdxs = []int32{
	0,  // 0: StatusResponse.status:type_name -> StatusResponse.Status
	2,  // 1: ControllerService.Status:input_type -> StatusRequest
	4,  // 2: ControllerService.RegisterDevice:input_type -> RegisterDeviceRequest
	6,  // 3: ControllerService.SendMessage:input_type -> SendMessageRequest
	7,  // 4: ControllerService.SendImageMessage:input_type -> SendImageMessageRequest
	1,  // 5: ControllerService.ReceiveMessage:input_type -> Empty
	10, // 6: ControllerService.GetWebhook:input_type -> GetWebhookRequest
	12, // 7: ControllerService.SaveWebhook:input_type -> SaveWebhookRequest
	13, // 8: ControllerService.DeleteWebhook:input_type -> DeleteWebhookRequest
	3,  // 9: ControllerService.Status:output_type -> StatusResponse
	5,  // 10: ControllerService.RegisterDevice:output_type -> RegisterDeviceResponse
	1,  // 11: ControllerService.SendMessage:output_type -> Empty
	8,  // 12: ControllerService.SendImageMessage:output_type -> SendImageMessageResponse
	9,  // 13: ControllerService.ReceiveMessage:output_type -> EventMessage
	11, // 14: ControllerService.GetWebhook:output_type -> GetWebhookResponse
	1,  // 15: ControllerService.SaveWebhook:output_type -> Empty
	1,  // 16: ControllerService.DeleteWebhook:output_type -> Empty
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_wadoh_proto_init() }
func file_proto_wadoh_proto_init() {
	if File_proto_wadoh_proto != nil {
		return
	}
	file_proto_wadoh_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wadoh_proto_rawDesc), len(file_proto_wadoh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wadoh_proto_goTypes,
		DependencyIndexes: file_proto_wadoh_proto_depIdxs,
		EnumInfos:         file_proto_wadoh_proto_enumTypes,
		MessageInfos:      file_proto_wadoh_proto_msgTypes,
	}.Build()
	File_proto_wadoh_proto = out.File
	file_proto_wadoh_proto_goTypes = nil
	file_proto_wadoh_proto_depIdxs = nil
}
